add_newline = true

scan_timeout = 10

[character]
success_symbol = "ğŸ¦„ [â¯](bold green)"
error_symbol = "ğŸ™…â€â™‚ï¸ [â¯](bold red)"

[package]
disabled = false

[username]
disabled = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[directory]
truncation_length = 0
truncate_to_repo = false

[memory_usage]
show_percentage = true
show_swap = true
threshold = -1
symbol = " "
separator = "/"
style = "bold dimmed green"

[env_var]
disabled = false

[time]
disabled = false
format = 'â³ [\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "local"
time_range = "10:00:00~14:00:00"

[docker_content]
symbol = "ğŸ³"

[aws]
style = "bold blue"
symbol = "ğŸ…°ï¸ "
display_items = "region"
[aws.region_aliases]
ap-southeast-2 = "au"
us-east-1 = "va"

[git_branch]
symbol = "ğŸŒ² "
truncation_length = 20
truncation_symbol = ""

[git_commit]
truncation_length = 30

[git_state]
progress_divider = " of "
cherry_pick = "ğŸ’ PICKING"

[git_status]
conflicted = "ğŸ˜±"
ahead = "ğŸğŸ’¨"
behind = "ğŸ˜“"
diverged = "ğŸ˜–"
untracked = "ğŸ˜³"
stashed = "ğŸ“¦"
modified = "ğŸ“"
staged.value = "++"
staged.style = "green"
staged_count_enabled = true
staged_count_style = "green"
renamed = "ğŸ’"
deleted = "ğŸ—‘"
